variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo

stages:
  - test
  - lint

test:nightly:
  image: rustdocker/rust:nightly
  stage: test
  before_script:
    - rustc --version
    - cargo --version
  script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  cache:
    paths:
      - .cargo

test:beta:
  image: rustdocker/rust:beta
  stage: test
  before_script:
    - rustc --version
    - cargo --version
  script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  cache:
    paths:
      - .cargo

test:stable:
  image: rustdocker/rust:stable
  stage: test
  before_script:
    - rustc --version
    - cargo --version
  script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  cache:
    paths:
      - .cargo

lint:
  image: rustdocker/rustfmt_clippy:nightly
  stage: lint
  before_script:
    - rustc --version
    - cargo --version
  script:
    - cargo clippy
  cache:
    paths:
      - .cargo

codestyle:
  image: rustdocker/rustfmt_clippy:nightly
  stage: lint
  before_script:
    - rustc --version
    - cargo --version
  script:
    - cargo fmt -- --check
  cache:
    paths:
      - .cargo