variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo

stages:
  - test
  - lint

test:nightly:
  image: rustlang/rust:nightly
  stage: test
  before_script:
    - rustc --version
    - cargo --version
  script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  cache:
    paths:
      - .cargo

lint:
  image: rustlang/rust:nightly
  stage: lint
  before_script:
    - rustc --version
    - cargo --version
  script:
    - rustup component add clippy
    - cargo clippy
  cache:
    paths:
      - .cargo

codestyle:
  image: rustlang/rust:nightly
  stage: lint
  before_script:
    - rustc --version
    - cargo --version
  script:
    - rustup component add rustfmt-preview
    - cargo fmt -- --check
  cache:
    paths:
      - .cargo
