variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo

test:nightly:
  image: rustdocker/rust:nightly
  before_script:
    - rustc --version
    - cargo --version
  script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  cache:
    paths:
      - .cargo

test:beta:
  image: rustdocker/rust:beta
  before_script:
    - rustc --version
    - cargo --version
  script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  cache:
    paths:
      - .cargo

test:stable:
  image: rustdocker/rust:stable
  before_script:
    - rustc --version
    - cargo --version
  script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  cache:
    paths:
      - .cargo

lint:
  image: rustdocker/rustfmt_clippy:stable
  before_script:
    - rustc --version
    - cargo --version
  script:
    - cargo clippy
  cache:
    paths:
      - .cargo

codestyle:
  image: rustdocker/rustfmt_clippy:stable
  before_script:
    - rustc --version
    - cargo --version
  script:
    - cargo fmt -- --check
  cache:
    paths:
      - .cargo

compare-benchmarks:
  image: rustdocker/rust:stable
  allow_failure: true
  except: [master]
  script:
    - apt-get update && apt-get install -y build-essential libboost-dev rsync jq curl gnuplot
    - cargo bench
  artifacts:
    paths: [bench/target/criterion]
    