language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
stages:
  - test
  - lint
  - codestyle
jobs:
  include:
    - stage: lint
      script:
        - rustup component add clippy
        - cargo clippy
    - stage: codestyle
      script:
        - rustup component add rustfmt-preview
        - cargo fmt -- --check
